---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesfrontend-deployment
  labels:
    app: sales-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-frontend
  template:
    metadata:
      labels:
        app: sales-frontend
    spec:
      containers:
        - name: sales-frontend
          image: jackjackzhou/sales-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sales-frontend-servies
spec:
  type: LoadBalancer
  ports:
  - port: 4006
    targetPort: 80
    protocol: TCP
    nodePort: 31006
  selector:
    app: sales-frontend
